# ===================================================
# Versión Limpia y Final
# ===================================================
services:
  rabbitmq:
    image: rabbitmq:3.13-management
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      # Asegúrate que estas variables están en la UI de Dokploy
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}

  swordPHP:
    image: ghcr.io/1ndoryu/kamplesv2:latest
    ports:
      - "8787:8787"
    depends_on:
      - rabbitmq

volumes:
  rabbitmq_data: