# ===================================================
# VERSIÓN DEFINITIVA: Solución para el BUG de Docker v27/v28
# ===================================================
services:
  rabbitmq:
    image: rabbitmq:3.13-management
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    networks:
      - kamples-net

  swordPHP:
    image: ghcr.io/1ndoryu/kamplesv2:latest
    ports:
      - "8787:8787"
    depends_on:
      - rabbitmq
    networks:
      - kamples-net

volumes:
  rabbitmq_data:

networks:
  kamples-net:
    driver: overlay
    ipam:
      driver: default
      config:
        # Forzamos un subnet único para evitar el BUG de Docker
        - subnet: 10.88.89.0/24