# ===================================================
# Contenido Final y Correcto para docker-compose.yml
# (Versión con red personalizada para evitar conflictos)
# ===================================================

services:
  # --- Servicio de RabbitMQ ---
  rabbitmq:
    image: rabbitmq:3.13-management
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    networks: # <--- Añadido
      - kamples-net

  # --- Servicio de tu Aplicación PHP ---
  swordPHP:
    image: ghcr.io/1ndoryu/kamplesv2:latest
    ports:
      - "8787:8787"
    depends_on:
      - rabbitmq
    networks: # <--- Añadido
      - kamples-net

# --- Definición de Volúmenes ---
volumes:
  rabbitmq_data:

# --- Definición de la Red Personalizada ---
networks: # <--- Sección completamente nueva
  kamples-net:
    driver: overlay
    ipam:
      driver: default
      config:
        - subnet: 10.88.89.0/24