# ===================================================
# Contenido Final y Correcto para docker-compose.yml
# ===================================================

services:
  # --- Servicio de RabbitMQ ---
  rabbitmq:
    image: rabbitmq:3.13-management
    ports:
      - "15672:15672" # Puerto para la interfaz de gestión web
      - "5672:5672"   # Puerto para la conexión de clientes (tu app)
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      # Estas variables DEBEN estar definidas en la sección "Environment Variables" de la UI de Dokploy.
      # Dokploy las inyectará aquí durante el despliegue.
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}

  # --- Servicio de tu Aplicación PHP ---
  swordPHP:
    # ESTA ES LA LÍNEA MÁS IMPORTANTE:
    # Apunta a la imagen que construiste y subiste a GitHub Packages.
    # Reemplazamos toda la sección 'build' por esta única línea.
    image: ghcr.io/1ndoryu/kamplesv2:latest

    ports:
      - "8787:8787" # Puerto que expone tu aplicación PHP
    depends_on:
      - rabbitmq # Asegura que RabbitMQ se inicie antes que tu aplicación

# --- Definición de Volúmenes ---
# Esto le dice a Docker que cree un volumen para guardar los datos de RabbitMQ.
volumes:
  rabbitmq_data: